### ISSUE TITLE
this is a nice construct to have students develop -- and a good place to write your future self an explanatory in-line comment

### ISSUE THREAD

**Issue by tofr** [hunter-teacher-cert/summer-2020-topics-project-ml-shift-ciphers#3]
https://github.com/hunter-teacher-cert/summer-2020-topics-project-ml-shift-ciphers/blob/e8a93bb50de6be2796b17e7cd0db28b1ddb8376e/ShiftCipher.java#L132

**Comment by malfano3** [comment]
Comment now added, thank you for the suggestion! We definitely struggled with this line for some time today, so I agree that a comment will go a long way when we look back in a day, week, month, or year.
